#!/bin/bash

echo "Atualizando Servidor....."
apt-get update
apt-get upgrade -y
apt-get install apache 2 -y
apt-get install unzip -y

echo "Baixando aquivos da aplicação.."

cd /tmp
wget https://ithub.com/denilsonbonatti/linux-site-dio/archive/refs/heads/main.zip
unzip main.zip
cd linux-site-dio-main
cp -R * /var/www/htm/
